---
name: Moduli merging workflow
on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * */6"
permissions:
  contents: read
jobs:
  Generate:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: Set current date as env variable
        run: echo CURRENT_DATE=$(date +'%Y%m%d') >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.head_ref }}

      - name: Install openssh-client
        run: |
          sudo apt-get install --assume-yes --no-install-recommends --update openssh-client

      - name: Generate 4096 bits moduli file
        run: |
          set -eu -o pipefail
          mkdir -p /tmp/moduli
          time ssh-keygen -M generate -O bits=4096 /tmp/moduli/moduli.4096-candidates
          time ssh-keygen -M screen -f /tmp/moduli/moduli.4096-candidates /tmp/moduli/moduli.4096

      - name: Download OpenSSH moduli file
        run: |
          set -eu -o pipefail
          curl -fsSL "https://raw.githubusercontent.com/openssh/openssh-portable/master/moduli" | grep -v '^#' > /tmp/moduli.tmp

      - name: Merge moduli files
        run: |
          set -eu -o pipefail
          grep -vE '^$|#' /tmp/moduli/moduli.4096 >> /tmp/moduli.tmp

      - name: Process moduli file
        run: |
          set -eu -o pipefail
          echo "# Generated at ${{ env.CURRENT_DATE }} from ${{ github.repositoryUrl }}" > ./moduli
          echo "# Timestamp Type Tests Trials Size Generator Modulus" >> ./moduli
          awk '$5 >= 4095' /tmp/moduli.tmp | grep -vE '^$|#'| sort -u >> ./moduli
          rm -v /tmp/moduli.tmp
          head -n5 ./moduli

      - name: Verify moduli file
        run: |
          set -eu -o pipefail
          grep -vE '^#|^$' moduli | shuf -n30 | ssh-keygen -M screen /tmp/mod.test
          grep "$(shuf -n5 /tmp/mod.test | awk '{print $NF}')" moduli || {
            echo "Moduli file verification failed"
            exit 1
          }

      - name: Upload moduli artifact
        if: ${{ github.ref_name == 'main' }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: moduli
          path: ./moduli

      - name: Commit and push moduli file
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        if: ${{ github.ref_name == 'main' }}
        with:
          commit_message: Updated moduli file - ${{ env.CURRENT_DATE }}
